---
secrets: (( merge ))
terraform_outputs: (( merge ))
meta:
  cpi-release: (( merge ))

  bosh_private_ip: (( merge || nil ))

  bosh_public_ip: (( merge ))

  bosh_service_ip: (( merge ))

  ntp: (( merge ))

  default_bosh_private_static_ips:
    - (( meta.bosh_private_ip ))
  default_bosh_public_static_ips:
    - (( meta.bosh_public_ip ))

  default_bosh_job_templates:
    - {name: nats, release: bosh}
    - {name: redis, release: bosh}
    - {name: postgres, release: bosh}
    - {name: blobstore, release: bosh}
    - {name: director, release: bosh}
    - {name: health_monitor, release: bosh}

  specific_bosh_job_templates: (( merge ))

  postgres:
    host: 127.0.0.1
    user: postgres
    password: (( secrets.bosh_postgres_password ))
    database: bosh
    adapter: postgres

  default_dns:
    address: (( meta.bosh_public_ip ))
    domain_name: microbosh
    db: (( meta.postgres ))
    recursor: 8.8.8.8

  default_agent:
    mbus: (( "nats://nats:" secrets.bosh_nats_password "@" meta.bosh_service_ip ":4222" ))

name: (( merge ))

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=207
  sha1: 5f835bad5fc46230cd2fa823c0a52a94829ee044
- (( meta.cpi-release ))

resource_pools: (( merge ))

disk_pools:
- name: disks
  disk_size: 32_768
  cloud_properties: (( merge ))

networks: (( merge ))

jobs:
- name: bosh
  instances: 1

  templates: (( meta.default_bosh_job_templates meta.specific_bosh_job_templates ))

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - name: private
    static_ips: (( merge || meta.default_bosh_private_static_ips ))
    default: [dns, gateway]
  - name: public
    static_ips: (( merge || meta.default_bosh_public_static_ips ))

  properties:
    compiled_package_cache:
      provider: s3
      options:
        access_key_id: (( terraform_outputs.compiled_cache_bucket_access_key_id ))
        secret_access_key: (( terraform_outputs.compiled_cache_bucket_secret_access_key ))
        bucket_name: shared-cf-bosh-blobstore
        host: (( terraform_outputs.compiled_cache_bucket_host ))

    nats:
      address: 127.0.0.1
      user: nats
      password: (( secrets.bosh_nats_password ))

    redis:
      listen_address: 127.0.0.1
      address: 127.0.0.1
      password: (( secrets.bosh_redis_password ))

    postgres: (( meta.postgres ))

    blobstore:
      address: (( meta.bosh_service_ip ))
      provider: dav
      director:
        user: director
        password: (( secrets.bosh_blobstore_director_password ))
      agent:
        user: agent
        password: (( secrets.bosh_agent_password ))
      options:
        endpoint: (( "http://" meta.bosh_public_ip ":25250" ))
        user: agent
        password: (( secrets.bosh_agent_password ))

    director:
      address: 127.0.0.1
      name: my-bosh
      db: (( meta.postgres ))
      cpi_job: cpi
      ignore_missing_gateway: "false"
      user_management:
        provider: local
        local:
          users:
            - { name: admin, password: (( secrets.bosh_admin_password )) }

    hm:
      director_account:
        user: admin
        password: (( secrets.bosh_hm_director_password ))
      resurrector_enabled: (( merge || "true" ))

    ntp: (( meta.ntp ))

    agent: (( merge || meta.default_agent ))

    registry:
      host: (( meta.bosh_service_ip ))
      db: (( meta.postgres ))
      http:
        # Variables used by official job release
        user: admin
        password: (( secrets.bosh_registry_password ))
      # Variables used by Google job release
      username: admin
      password: (( secrets.bosh_registry_password ))

    dns: (( merge || meta.default_dns ))

    <<: (( merge ))


properties: (( merge || nil ))

cloud_provider:
  template: (( merge ))

  ssh_tunnel:
    host: (( meta.bosh_service_ip ))
    port: 22
    user: vcap
    private_key: .ssh/id_rsa

  mbus: (( "https://mbus:mbus@" meta.bosh_service_ip  ":6868" ))

  properties: (( merge ))
