meta:
  bosh_uaa_url: (( concat "https://" terraform_outputs.microbosh_static_private_ip ":8443" ))
  postgres:
    additional_databases: [uaa]

releases:
- name: uaa
  url: https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=3
  sha1: 90976d62aec3db7e543983ac38bf7d02f4ab8004

jobs:
- name: bosh
  templates:
  - name: uaa
    release: uaa

  properties:
    login:
      saml:
        serviceProviderKey: (( grab secrets.bosh_login_saml_serviceProviderKey ))
        serviceProviderCertificate: (( grab secrets.bosh_login_saml_serviceProviderCertificate ))
    uaa:
      url: (( grab meta.bosh_uaa_url ))
      scim:
        users: (( grab secrets.bosh_uaa_scim_users ))

      clients:
        bosh_cli:
          override: true
          authorized-grant-types: password,refresh_token
          # scopes the client may receive
          scope: openid,bosh.admin,bosh.read,bosh.*.admin,bosh.*.read
          authorities: uaa.none
          access-token-validity: 600 # 10 min
          refresh-token-validity: 86400 # re-login required once a day
          secret: ""

      admin:
        client_secret: (( grab secrets.bosh_uaa_admin_client_secret ))
      login:
        client_secret: (( grab secrets.bosh_uaa_login_client_secret))
      zones: {internal: {hostnames: []}}
      sslCertificate: (( grab secrets.bosh_uaa_sslCertificate ))

      sslPrivateKey: (( grab secrets.bosh_uaa_sslPrivateKey ))

      jwt:
        signing_key: (( grab secrets.bosh_uaa_jwt_signing_key ))

        verification_key: (( grab secrets.bosh_uaa_jwt_verification_key ))

    uaadb:
      address: (( grab meta.postgres.host ))
      port: 5432
      db_scheme: postgresql
      databases:
      - {tag: uaa, name: uaa}
      roles:
      - tag: admin
        name: postgres
        password: (( grab meta.postgres.password ))

    director:
      ssl:
        key: (( grab secrets.bosh_director_ssl_key ))
        cert: (( grab secrets.bosh_director_ssl_cert ))

      user_management:
        provider: uaa
        local: ~
        uaa:
          url: (( grab meta.bosh_uaa_url ))
          public_key: (( grab secrets.bosh_director_uaa_public_key ))

    hm:
      director_account:
        ca_cert: (( grab secrets.bosh_hm_director_account_ca_cert ))
