---
terraform_outputs: (( merge ))

meta:
  bosh_private_ip: (( terraform_outputs.microbosh_static_private_ip ))
  bosh_public_ip: (( terraform_outputs.microbosh_static_public_ip ))
  bosh_service_ip: (( bosh_private_ip ))

  aws:
    access_key_id: (( terraform_outputs.aws_access_key_id ))
    secret_access_key: (( terraform_outputs.aws_secret_access_key ))
    default_key_name: (( terraform_outputs.key_pair_name ))
    default_security_groups:
    - (( terraform_outputs.default_security_group ))
    region: (( terraform_outputs.region ))

  cpi-release:
    name: bosh-aws-cpi
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=28
    sha1: c7ce03393ebedd87a860dc609758ddb9654360fa

  specific_bosh_job_templates:
    - {name: registry, release: bosh}
    - {name: cpi, release: bosh-aws-cpi}

  ntp:
  - 0.pool.ntp.org
  - 1.pool.ntp.org


name: bosh

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3074
    sha1: 1a29c43d4e8abf7476ed6bb83168df1bdb742022
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk: {size: 40_000, type: gp2}
    availability_zone: (( terraform_outputs.zone0 ))

disk_pools:
- name: disks
  cloud_properties:
    type: gp2

networks:
- name: private
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns: [10.0.0.2]
    cloud_properties:
      subnet: (( terraform_outputs.bosh_subnet_id ))
      security_groups:
      - (( terraform_outputs.bosh_security_group ))
- name: public
  type: vip

jobs:
- name: bosh

  properties:
    hm:
      resurrector_enabled: true

    aws: (( meta.aws ))

    dns: null

cloud_provider:
  template:
    name: cpi
    release: bosh-aws-cpi

  properties:
    aws: (( meta.aws ))
    agent:
      mbus: "https://mbus:mbus@0.0.0.0:6868"
    blobstore:
      provider: local
      path: /var/vcap/micro_bosh/data/cache
    ntp: (( meta.ntp ))

