collectd:
  name: collectd
  release: collectd

jobs:
  - <<: (( merge ))
  - name: consul_z1
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: consul_z2
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: ha_proxy_z1
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: nats_z1
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: nats_z2
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: etcd_z1
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: etcd_z2
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: stats_z1
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: nfs_z1
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: postgres_z1
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: uaa_z1
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: uaa_z2
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: api_z1
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: api_z2
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: clock_global
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: api_worker_z1
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: api_worker_z2
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: hm9000_z1
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: hm9000_z2
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: runner_z1
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: runner_z2
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: loggregator_z1
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: loggregator_z2
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: doppler_z1
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: doppler_z2
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: loggregator_trafficcontroller_z1
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: loggregator_trafficcontroller_z2
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: router_z1
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))
  - name: router_z2
    <<: (( merge ))
    templates:
      - <<: (( merge ))
      - (( collectd ))

  # Two below are defined here just to preserve job ordering
  - name: acceptance_tests
    <<: (( merge ))
  - name: smoke_tests
    <<: (( merge ))

properties:
  <<: (( merge ))
  collectd:
    interval: 10
  graphite:
    server: changeme
    prefix: "servers."
