---
terraform_outputs: ((merge))
secrets: (( merge ))
director_uuid: BOSH_UUID
name: (( merge ))
meta:
  <<: (( merge ))
  default_env:
    bosh:
      password: (( secrets.vcap_password ))

update:
  serial: false # makes every job deploy at the same time.

jobs:
  - name: api_worker_z1
    instances: 0
  - name: runner_z1
    instances: 1
  - name: runner_z2
    instances: 1
  - name: consul_z1
    instances: 1
    update:
      serial: false
  - name: consul_z2
    instances: 0
    update:
      serial: false
  - name: stats_z1
    instances: 1

properties:
  # FIXME: Starting v218 consul has SSL enabled by default, but
  # we must provide the certificates.
  # For testing, we had explicitelly disable consul SSL.
  consul:
    require_ssl: false
  cc:
    staging_upload_user: username
    staging_upload_password: (( secrets.staging_upload_password ))
    bulk_api_password: (( secrets.bulk_api_password ))
    db_encryption_key: (( secrets.cc_db_encryption_key ))
    min_cli_version: '6.1.0'
    min_recommended_cli_version: '6.10.0'
  nats:
    user: nats_user
    password: (( secrets.nats_password ))
  dea_next:
    disk_mb: 10240
    memory_mb: 4096
  router:
    enable_ssl: true
    ssl_cert: (( secrets.router_ssl_cert ))
    ssl_key: (( secrets.router_ssl_key ))
    cipher_suites: TLS_RSA_WITH_RC4_128_SHA:TLS_RSA_WITH_AES_128_CBC_SHA
    status:
      user: router_user
      password: (( secrets.router_password ))
  uaa:
    admin:
      client_secret: (( secrets.uaa_admin_client_secret ))
    batch:
      username: batch_username
      password: (( secrets.uaa_batch_password ))
    cc:
      client_secret: (( secrets.uaa_cc_client_secret ))
    clients:
      app-direct:
        secret: (( secrets.uaa_clients_app_direct_secret ))
      graphite-nozzle:
        access-token-validity: 1209600
        authorized-grant-types: authorization_code,client_credentials,refresh_token
        override: true
        secret: (( secrets.uaa_clients_firehose_password ))
        scope: openid,oauth.approvals,doppler.firehose
        authorities: oauth.login,doppler.firehose
      developer_console:
        secret: (( secrets.uaa_clients_developer_console_secret ))
      login:
        secret: (( secrets.uaa_clients_login_secret ))
      notifications:
        secret: (( secrets.uaa_clients_notifications_secret ))
      doppler:
        secret: (( secrets.uaa_clients_doppler_secret ))
      cloud_controller_username_lookup:
        secret: (( secrets.uaa_clients_cloud_controller_username_lookup_secret ))
      gorouter:
        secret: (( secrets.uaa_clients_gorouter_secret ))
    jwt:
      signing_key: (( secrets.uaa_jwt_signing_key ))
      verification_key: (( secrets.uaa_jwt_verification_key ))
    scim:
      users:
      - (( "admin|" secrets.uaa_admin_password "|scim.write,scim.read,openid,cloud_controller.admin,doppler.firehose" ))

  login:
    links:
      network: https://network.gopivotal.com/login
      signup-network: https://network.gopivotal.com/registrations/new
    smtp:
      host: localhost
      port: 2525

  loggregator_endpoint:
    shared_secret: (( secrets.loggregator_endpoint_shared_secret ))

  ccdb:
    db_scheme: postgres
    address: (( properties.databases.address ))
    port: (( properties.databases.port ))
    roles:
      - tag: admin
        name: ccadmin
        password: (( secrets.ccadmin_password ))
    databases:
      - tag: cc
        name: ccdb
        citext: true

  uaadb:
    db_scheme: postgresql
    address: (( properties.databases.address ))
    port: (( properties.databases.port ))
    roles:
      - tag: admin
        name: uaaadmin
        password: (( secrets.uuadmin_password ))
    databases:
      - tag: uaa
        name: uaadb
        citext: true

  databases:
    db_scheme: postgres
    address: (( merge ))
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: (( secrets.ccadmin_password ))
      - tag: admin
        name: uaaadmin
        password: (( secrets.uuadmin_password ))
    databases:
      - tag: cc
        name: ccdb
        citext: true
      - tag: uaa
        name: uaadb
        citext: true
