---
#
# This template modifies the upstream diego.yml to add more desired
# properties and VMS
#
property_overrides: (( merge ))
instance_count_overrides: (( merge ))

properties:
  <<: (( merge ))
  diego:
    <<: ((merge))
    executor:
      <<: (( merge ))
      memory_capacity_mb: (( property_overrides.executor.memory_capacity_mb || nil ))
      disk_capacity_mb: (( property_overrides.executor.disk_capacity_mb || nil ))
      create_work_pool_size: (( property_overrides.executor.create_work_pool_size || nil ))
    tps:
      <<: (( merge ))
      watcher: (( property_overrides.diego.tps.watcher ))

networks: (( merge ))

# Add a new
jobs:
  - <<: (( merge ))
  # A job with all the collocated services but cell related ones.
  - name: colocated_services_z1
    templates: (( base_job_templates.colocated_services ))
    instances: (( instance_count_overrides.colocated_services_z1.instances || 0 ))
    persistent_disk: (( persistent_disk_overrides.colocated_services_z1 || 1024 ))
    resource_pool: colocated_z1
    networks:
      - name: diego1
        static_ips: (( merge || static_ips(11,12,13,14,15,16,17,18,19,20) ))
    update:
      serial: true
      max_in_flight: 1
    properties:
      consul:
        agent:
          services:
            auctioneer: {}
            bbs: {}
            cc_uploader: {}
            etcd: {}
            file_server: {}
            nsync: {}
            receptor: {}
            ssh_proxy: {}
            stager: {}
            tps: {}
      diego:
        rep:
          zone: z1
      metron_agent:
        zone: z1

base_job_templates:
  <<: (( merge ))
  colocated_services:
    - name: auctioneer
      release: diego
    - name: bbs
      release: diego
    - name: cc_uploader
      release: diego
    - name: converger
      release: diego
    - name: consul_agent
      release: cf
    - name: etcd
      release: diego
    - name: file_server
      release: diego
    - name: nsync
      release: diego
    - name: route_emitter
      release: diego
    - name: ssh_proxy
      release: diego
    - name: tps
      release: diego
    - name: receptor
      release: diego
    - name: stager
      release: diego
    - name: metron_agent
      release: cf

