meta:
  environment: ~

lamb_meta:
  release:
    name: cf

  loggregator_templates:
  - name: doppler
    release: (( grab lamb_meta.release.name ))
  - name: syslog_drain_binder
    release: (( grab lamb_meta.release.name ))
  - name: metron_agent
    release: (( grab lamb_meta.release.name ))

  loggregator_trafficcontroller_templates:
  - name: loggregator_trafficcontroller
    release: (( grab lamb_meta.release.name ))
  - name: metron_agent
    release: (( grab lamb_meta.release.name ))
  - name: route_registrar
    release: (( grab lamb_meta.release.name ))

jobs:
- name: loggregator_z1
  properties:
    doppler:
      zone: z1
    metron_agent:
      zone: z1

- name: loggregator_z2
  properties:
    doppler:
      zone: z2
    metron_agent:
      zone: z2

- name: doppler_z1
  properties:
    doppler:
      zone: z1
    metron_agent:
      zone: z1

- name: doppler_z2
  properties:
    doppler:
      zone: z2
    metron_agent:
      zone: z2

- name: loggregator_trafficcontroller_z1
  properties:
    traffic_controller:
      zone: z1
    metron_agent:
      zone: z1
    route_registrar:
      routes:
      - name: doppler
        port: (( grab properties.loggregator.outgoing_dropsonde_port ))
        uris:
        - (( concat "doppler." properties.domain ))
      - name: loggregator
        port: (( grab properties.traffic_controller.outgoing_port ))
        uris:
        - (( concat "loggregator." properties.domain ))

- name: loggregator_trafficcontroller_z2
  properties:
    traffic_controller:
      zone: z2
    metron_agent:
      zone: z2
    route_registrar:
      routes:
      - name: doppler
        port: (( grab properties.loggregator.outgoing_dropsonde_port ))
        uris:
        - (( concat "doppler." properties.domain ))
      - name: loggregator
        port: (( grab properties.traffic_controller.outgoing_port ))
        uris:
        - (( concat "loggregator." properties.domain ))

properties:

  loggregator:
    maxRetainedLogMessages: 100
    debug: false
    blacklisted_syslog_ranges: ~
    outgoing_dropsonde_port: 8081
    dropsonde_incoming_port: 3457
    traffic_controller_url: (( concat "wss://doppler." properties.system_domain ":443" ))
    tls:
      ca: ~

  doppler:
    maxRetainedLogMessages: 100
    debug: false
    blacklisted_syslog_ranges: ~
    unmarshaller_count: 5
    port: 443
    enable_tls_transport: ~
    tls_server:
      cert: ~
      port: ~
      key: ~

  metron_agent:
    deployment: (( grab meta.environment ))
    preferred_protocol: ~
    dropsonde_incoming_port: (( grab properties.loggregator.dropsonde_incoming_port ))
    tls_client:
      cert: ~
      key: ~

  traffic_controller:
    outgoing_port: 8080
