---
terraform_outputs: (( merge ))
name: (( "cloudfoundry-" meta.environment ))
meta:
  environment: (( terraform_outputs.environment ))
  zones:
    z1: (( terraform_outputs.zone0 ))
    z2: (( terraform_outputs.zone1 ))
  fog_config:
    region: (( terraform_outputs.region ))

networks:
- name: cf1
  subnets:
    - range: 10.0.10.0/24
      gateway: 10.0.10.1
      dns: [10.0.0.2]
      reserved:
      - 10.0.10.2 - 10.0.10.9
      static:
      - 10.0.10.10 - 10.0.10.40
      cloud_properties:
        subnet: (( terraform_outputs.cf1_subnet_id ))
- name: cf2
  subnets:
    - range: 10.0.11.0/24
      gateway: 10.0.11.1
      dns: [10.0.0.2]
      reserved:
      - 10.0.11.2 - 10.0.11.9
      static:
      - 10.0.11.10 - 10.0.11.40
      cloud_properties:
        subnet: (( terraform_outputs.cf2_subnet_id ))

resource_pools:
  - name: router_z1
    cloud_properties:
      elbs:
      - (( terraform_outputs.elb_name ))
  - name: router_z2
    cloud_properties:
      elbs:
      - (( terraform_outputs.elb_name ))

properties:
  graphite:
    server: 10.0.10.40
  domain: (( terraform_outputs.environment ".cf.paas.alphagov.co.uk" ))
  collector:
    graphite:
      address: 10.0.10.40
  cc:
    droplets:
      droplet_directory_key: (( terraform_outputs.environment "-cf-droplets" ))
    buildpacks:
      buildpack_directory_key: (( terraform_outputs.environment "-cf-buildpacks" ))
    resource_pool:
      resource_directory_key: (( terraform_outputs.environment "-cf-resources" ))
    packages:
      app_package_directory_key: (( terraform_outputs.environment "-cf-packages" ))
  template_only:
    aws:
      access_key_id: (( terraform_outputs.aws_access_key_id ))
      secret_access_key: (( terraform_outputs.aws_secret_access_key ))
      availability_zone: (( terraform_outputs.zone0 ))
      availability_zone2: (( terraform_outputs.zone1 ))
  databases:
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
  syslog_daemon_config:
    address: 10.0.40.10
    port: 2514
    transport: relp

jobs:
  - name: postgres_z1
    instances: 1
    networks:
    - name: cf1
      static_ips: (( static_ips(7) ))

